on: 
  workflow_dispatch:
    inputs:
      id:
        description: 'explicitly provided id for workflow run'     
        required: true
name: Deploy to test
jobs:
  id:
    runs-on: ubuntu-latest
    steps:
    - name: ${{ github.event.inputs.id }}
      run: exit 0
  porter-deploy:
    runs-on: ubuntu-latest
    needs: id
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set Github tag
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Setup porter
      uses: porter-dev/setup-porter@v0.1.0
    - name: Deploy stack
      timeout-minutes: 30
      run: exec porter apply -f ./porter.yaml
      env:
        PORTER_CLUSTER: "142"
        PORTER_HOST: https://dashboard.internal-tools.porter.run
        PORTER_PR_NUMBER: ${{ github.event.number }}
        PORTER_PROJECT: "301"
        PORTER_STACK_NAME: test
        PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
        PORTER_TOKEN: ${{ secrets.PORTER_STACK_301_142 }}
