"on":
    push:
        branches:
            - master
name: Deploy to docker
jobs:
    porter-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Set Github tag
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            - name: Setup porter
              uses: porter-dev/setup-porter@v0.1.0
            - name: Deploy stack
              timeout-minutes: 30
              run: porter apply
              env:
                PORTER_APP_NAME: docker
                PORTER_CLUSTER: "327"
                PORTER_DEPLOYMENT_TARGET_ID: 27a7bece-b219-490a-a9ed-510fc20c9728
                PORTER_HOST: https://dashboard.internal-tools.porter.run
                PORTER_PROJECT: "8"
                PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
                PORTER_TOKEN: ${{ secrets.PORTER_APP_8_717225443 }}
